import React, { useState, useEffect } from 'react';
import { Sparkles, Merge, BookOpen, Loader2, ArrowRight } from 'lucide-react';
import { Novel } from '../types';
import { getLibrary, getHistory } from '../services/storageService';
import { generateCrossoverAI } from '../services/geminiService';
import NovelCard from '../components/NovelCard';

interface NexusProps {
    addToast: (msg: string, type: 'success' | 'error' | 'info') => void;
}

const Nexus: React.FC<NexusProps> = ({ addToast }) => {
    const [availableNovels, setAvailableNovels] = useState<Novel[]>([]);
    const [selection, setSelection] = useState<(Novel | null)[]>([null, null]);
    const [crossoverContent, setCrossoverContent] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        // Combine library and history, deduplicate by ID
        const lib = getLibrary();
        const hist = getHistory();
        const combined = [...lib, ...hist];
        const unique = Array.from(new Map(combined.map(item => [item.id, item])).values());
        setAvailableNovels(unique);
    }, []);

    const handleSelect = (novel: Novel, index: 0 | 1) => {
        const newSel = [...selection];
        newSel[index] = novel;
        setSelection(newSel);
    };

    const handleConverge = async () => {
        if (!selection[0] || !selection[1]) return;
        setLoading(true);
        setCrossoverContent(null);
        
        const content = await generateCrossoverAI(selection[0], selection[1]);
        setCrossoverContent(content);
        
        setLoading(false);
        addToast("Timelines successfully merged.", "success");
    };

    return (
        <div className="max-w-6xl mx-auto min-h-[80vh] animate-fade-in p-4">
             <div className="text-center mb-12">
                <h1 className="text-4xl font-bold text-white mb-4 flex items-center justify-center gap-3">
                    <Sparkles className="text-purple-500 w-8 h-8" /> The Nexus
                </h1>
                <p className="text-gray-400 max-w-2xl mx-auto">
                    A dimensional rift where stories collide. Select two novels from your collection to witness a "What If" crossover event generated by the OmniRead Core.
                </p>
            </div>

            {/* Selection Area */}
            <div className="flex flex-col md:flex-row items-center justify-center gap-8 mb-12">
                {/* Slot 1 */}
                <div className="w-full max-w-xs flex flex-col gap-4">
                    <div className="bg-gray-900 border-2 border-dashed border-gray-700 rounded-2xl aspect-[2/3] flex items-center justify-center relative overflow-hidden group hover:border-purple-500/50 transition-colors">
                        {selection[0] ? (
                            <img src={selection[0].coverUrl} alt="Cover 1" className="w-full h-full object-cover" />
                        ) : (
                            <div className="text-gray-600 flex flex-col items-center">
                                <BookOpen className="w-12 h-12 mb-2" />
                                <span className="font-bold">Select World A</span>
                            </div>
                        )}
                        <select 
                            className="absolute inset-0 opacity-0 cursor-pointer"
                            onChange={(e) => {
                                const n = availableNovels.find(x => x.id === e.target.value);
                                if (n) handleSelect(n, 0);
                            }}
                        >
                            <option value="">Select Novel...</option>
                            {availableNovels.map(n => <option key={n.id} value={n.id}>{n.title}</option>)}
                        </select>
                    </div>
                    {selection[0] && <h3 className="text-center font-bold text-white truncate">{selection[0].title}</h3>}
                </div>

                {/* Convergence Button */}
                <div className="flex flex-col items-center gap-4">
                     <button 
                        onClick={handleConverge}
                        disabled={loading || !selection[0] || !selection[1]}
                        className={`w-20 h-20 rounded-full flex items-center justify-center shadow-[0_0_30px_rgba(168,85,247,0.4)] transition-all transform hover:scale-110 disabled:opacity-50 disabled:scale-100 ${loading ? 'bg-gray-800' : 'bg-gradient-to-br from-purple-600 to-blue-600'}`}
                     >
                         {loading ? <Loader2 className="w-8 h-8 text-white animate-spin" /> : <Merge className="w-8 h-8 text-white" />}
                     </button>
                     {loading && <span className="text-purple-400 text-sm font-bold animate-pulse">Merging Realities...</span>}
                </div>

                {/* Slot 2 */}
                <div className="w-full max-w-xs flex flex-col gap-4">
                    <div className="bg-gray-900 border-2 border-dashed border-gray-700 rounded-2xl aspect-[2/3] flex items-center justify-center relative overflow-hidden group hover:border-blue-500/50 transition-colors">
                        {selection[1] ? (
                            <img src={selection[1].coverUrl} alt="Cover 2" className="w-full h-full object-cover" />
                        ) : (
                            <div className="text-gray-600 flex flex-col items-center">
                                <BookOpen className="w-12 h-12 mb-2" />
                                <span className="font-bold">Select World B</span>
                            </div>
                        )}
                        <select 
                            className="absolute inset-0 opacity-0 cursor-pointer"
                            onChange={(e) => {
                                const n = availableNovels.find(x => x.id === e.target.value);
                                if (n) handleSelect(n, 1);
                            }}
                        >
                            <option value="">Select Novel...</option>
                            {availableNovels.map(n => <option key={n.id} value={n.id}>{n.title}</option>)}
                        </select>
                    </div>
                    {selection[1] && <h3 className="text-center font-bold text-white truncate">{selection[1].title}</h3>}
                </div>
            </div>

            {/* Result Area */}
            {crossoverContent && (
                <div className="max-w-3xl mx-auto bg-gray-900 border border-gray-800 rounded-2xl p-8 shadow-2xl relative overflow-hidden animate-slide-up">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 to-blue-500"></div>
                    <div className="prose prose-invert max-w-none font-serif text-lg leading-relaxed">
                        <h2 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-blue-400 mb-6 text-center">
                            Convergence Log #{(Math.random()*1000).toFixed(0)}
                        </h2>
                        <div dangerouslySetInnerHTML={{ __html: crossoverContent }} />
                    </div>
                </div>
            )}
        </div>
    );
};

export default Nexus;
